/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionDayIdRouteImport } from './routes/session.$dayId'
import { Route as PlanDayIdRouteImport } from './routes/plan.$dayId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDayIdRoute = SessionDayIdRouteImport.update({
  id: '/session/$dayId',
  path: '/session/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDayIdRoute = PlanDayIdRouteImport.update({
  id: '/$dayId',
  path: '/$dayId',
  getParentRoute: () => PlanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/plan/$dayId': typeof PlanDayIdRoute
  '/session/$dayId': typeof SessionDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/plan/$dayId': typeof PlanDayIdRoute
  '/session/$dayId': typeof SessionDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/plan/$dayId': typeof PlanDayIdRoute
  '/session/$dayId': typeof SessionDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/history'
    | '/plan'
    | '/progress'
    | '/settings'
    | '/tools'
    | '/plan/$dayId'
    | '/session/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/history'
    | '/plan'
    | '/progress'
    | '/settings'
    | '/tools'
    | '/plan/$dayId'
    | '/session/$dayId'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/history'
    | '/plan'
    | '/progress'
    | '/settings'
    | '/tools'
    | '/plan/$dayId'
    | '/session/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRoute
  HistoryRoute: typeof HistoryRoute
  PlanRoute: typeof PlanRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  SessionDayIdRoute: typeof SessionDayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$dayId': {
      id: '/session/$dayId'
      path: '/session/$dayId'
      fullPath: '/session/$dayId'
      preLoaderRoute: typeof SessionDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$dayId': {
      id: '/plan/$dayId'
      path: '/$dayId'
      fullPath: '/plan/$dayId'
      preLoaderRoute: typeof PlanDayIdRouteImport
      parentRoute: typeof PlanRoute
    }
  }
}

interface PlanRouteChildren {
  PlanDayIdRoute: typeof PlanDayIdRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanDayIdRoute: PlanDayIdRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRoute,
  HistoryRoute: HistoryRoute,
  PlanRoute: PlanRouteWithChildren,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  SessionDayIdRoute: SessionDayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
